### ISSUE TITLE
Minor Roxygen typo

### ISSUE THREAD

**Issue by maptracker** [welch16/ChIPexoQual#5]
`calculateSummary()` has an [Roxygen block](https://github.com/welch16/ChIPexoQual/blob/master/R/base_summaryStats.R#L6-L19) prefixed with `##` rather than `#'` or `##'`. This will presumably keep it from being built into [man/](https://github.com/welch16/ChIPexoQual/tree/master/man).

I just caught it while casual browsing, you might want to `grep '^## ' R/*.R` the files to look for other examples...

**Comment by welch16** [comment]
Thanks for the feedback, already fixed it
